import Link from "next/link";
import { notFound } from "next/navigation";

import { MonitoringCheckForm } from "@/components/monitoring-check-form";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { getMonitoringForApp } from "@/lib/app-service";

export default async function MonitoringPage({ params, searchParams }: PageProps<"/stores/[storeId]/monitoring">) {
  const { storeId } = await params;
  const { run, completedRun } = await searchParams;
  const data = await getMonitoringForApp(storeId, typeof run === "string" ? run : undefined);
  if (!data) notFound();
  const { store, targets, report } = data;
  return <div className="space-y-8">
    <nav aria-label="Breadcrumb" className="text-sm text-muted-foreground"><Link href="/stores" className="hover:text-foreground">Stores</Link><span aria-hidden="true"> / </span><Link href={`/stores/${store.id}`} className="hover:text-foreground">{store.name}</Link><span aria-hidden="true"> / </span><span className="text-foreground">Monitoring</span></nav>
    <header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between">
      <div><p className="text-xs font-semibold tracking-wide text-muted-foreground uppercase">{store.name}</p><h1 className="mt-2 font-heading text-3xl font-semibold tracking-tight">Monitoring</h1><p className="mt-2 text-sm text-muted-foreground">Confirmed store quality over time.</p></div>
      {report && <MonitoringCheckForm storeId={store.id} referenceRunId={report.latestAttempt.id} disabled={!report.canRunCheck} scopeLabel={scopeLabel(report.scope)} selectedPdpCount={report.scope.executionLimit} />}
    </header>
    {!targets.length ? <Card className="border-dashed"><CardHeader><CardTitle>No monitoring history yet</CardTitle><CardDescription>Start a scoped Store Audit from the Catalog. Its first complete check establishes a baseline.</CardDescription></CardHeader><CardContent><Button asChild><Link href={`/stores/${store.id}/catalog`}>Open catalog</Link></Button></CardContent></Card> : <>
    <section aria-labelledby="targets-title" className="space-y-3"><h2 id="targets-title" className="font-heading text-xl font-semibold">Monitored scopes</h2><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{targets.map((target) => <Link key={target.referenceRunId} href={`/stores/${store.id}/monitoring?run=${target.referenceRunId}`} className="rounded-xl border border-border bg-card p-4 transition-colors hover:bg-muted focus-visible:outline-none focus-visible:ring-3 focus-visible:ring-ring/50"><p className="font-semibold">{scopeLabel(target.scope)}</p><p className="mt-1 text-sm text-muted-foreground">{target.lastConfirmed ? `${target.lastConfirmed.summary?.issueCount ?? 0} current issues` : "No confirmed check"}</p><p className="mt-2 text-xs text-muted-foreground">Last attempt {format(target.latestAttempt.startedAt)}</p></Link>)}</div></section>
      {report && <MonitoringDetail storeId={store.id} report={report} completedRunId={typeof completedRun === "string" ? completedRun : undefined} />}
    </>}
  </div>;
}

function MonitoringDetail({ storeId, report, completedRunId }: { storeId: string; report: NonNullable<Awaited<ReturnType<typeof getMonitoringForApp>>>["report"]; completedRunId?: string }) {
  if (!report) return null;
  return <div className="space-y-8">
    {completedRunId === report.latestAttempt.id && <CompletionSummary storeId={storeId} report={report} />}
    <section className="grid gap-4 sm:grid-cols-3"><Metric label="Scope" value={scopeLabel(report.scope)} detail={`${report.lastConfirmed?.scope.matchingPdpCount ?? report.latestAttempt.scope.matchingPdpCount} matching PDPs`} /><Metric label="Current issues" value={report.lastConfirmed ? String(report.currentIssues.length) : "Unknown"} detail={report.lastConfirmed ? `Confirmed ${format(report.lastConfirmed.completedAt)}` : "No complete check yet"} /><Metric label="Coverage" value={`${report.lastConfirmed?.completedPdpCount ?? 0} / ${report.lastConfirmed?.selectedPdpCount ?? 0}`} detail="PDPs checked" /></section>
    <section className="space-y-4"><div><h2 className="font-heading text-xl font-semibold">Current confirmed state</h2><p className="mt-1 text-sm text-muted-foreground">{report.lastConfirmed ? `Based on the complete check from ${format(report.lastConfirmed.completedAt)}.` : "A complete catalog check is required before quality can be confirmed."}</p></div>{report.lastConfirmed && !report.comparisonPredecessor && <Card className="border-dashed"><CardHeader><CardTitle>{report.comparisonUnavailable ? "Comparison unavailable" : "Baseline established"}</CardTitle><CardDescription>{report.comparisonUnavailable ? "The catalog selection or checks changed, so this result is confirmed but not compared with earlier checks." : "This is the first comparable complete check. Changes will appear after a later comparable check."}</CardDescription></CardHeader></Card>}{report.changes && <div className="grid grid-cols-2 gap-3 sm:grid-cols-4"><Metric label="New" value={String(report.changes.new)} /><Metric label="Existing" value={String(report.changes.unchanged)} /><Metric label="Resolved" value={String(report.changes.resolved)} /><Metric label="Regressed" value={String(report.changes.regressed)} /></div>}</section>
    <section className="space-y-4"><div><h2 className="font-heading text-xl font-semibold">Current issues</h2><p className="mt-1 text-sm text-muted-foreground">Only active issues from the last confirmed check.</p></div>{report.currentIssues.length ? <div className="divide-y divide-border rounded-xl border border-border bg-card">{report.currentIssues.map((issue) => <article key={issue.ruleId} className="space-y-3 p-4"><div className="flex flex-wrap items-center gap-2"><Badge variant={issue.severity}>{issue.severity}</Badge>{issue.lifecycle && <Badge variant="secondary" className="capitalize">{issue.lifecycle}</Badge>}<span className="font-mono text-xs text-muted-foreground">{issue.ruleId}</span></div><h3 className="font-heading font-semibold">{issue.title}</h3><p className="text-sm text-muted-foreground">Affected now: {issue.affectedPdpCount} PDPs · First seen {format(issue.firstSeenAt)} · Last seen {format(issue.lastSeenAt)}</p><p className="text-xs text-muted-foreground">{issue.history.map((entry) => `${format(entry.completedAt)} — ${entry.lifecycle}`).join(" · ")}</p>{issue.affectedPdps.slice(0, 1).map((pdp) => <Button key={pdp.auditRunId} variant="ghost" size="sm" asChild><Link href={`/runs/${pdp.auditRunId}`}>Finding &amp; evidence</Link></Button>)}</article>)}</div> : <Card className="border-dashed"><CardHeader><CardTitle>{report.lastConfirmed ? "No current issues" : "No confirmed state"}</CardTitle><CardDescription>{report.lastConfirmed ? "All deterministic checks passed for the last complete bounded check." : "Partial and failed checks never imply that issues are gone."}</CardDescription></CardHeader></Card>}</section>
    <section className="space-y-4"><div><h2 className="font-heading text-xl font-semibold">Latest attempt</h2><p className="mt-1 text-sm text-muted-foreground">{report.latestAttempt.status.replaceAll("_", " ")} · {report.latestAttempt.completedPdpCount} / {report.latestAttempt.selectedPdpCount} PDPs checked · {format(report.latestAttempt.completedAt ?? report.latestAttempt.startedAt)}</p></div>{report.latestAttempt.id !== report.lastConfirmed?.id && <Card className="border-dashed"><CardHeader><CardTitle>{report.latestAttempt.status === "failed" ? "Check failed" : report.latestAttempt.status === "queued" ? "Check queued" : report.latestAttempt.status === "running" ? "Check running" : "Partial check"}</CardTitle><CardDescription>{report.lastConfirmed ? "The latest check was incomplete. The confirmed issue state was preserved." : "No confirmed issue state was established."}</CardDescription></CardHeader><CardContent><Button variant="outline" asChild><Link href={`/stores/${storeId}/quality/${report.latestAttempt.id}`}>View run</Link></Button></CardContent></Card>}</section>
    <section className="space-y-4"><div><h2 className="font-heading text-xl font-semibold">History</h2><p className="mt-1 text-sm text-muted-foreground">The latest 20 checks for this scope.</p></div><div className="divide-y divide-border rounded-xl border border-border bg-card">{report.history.map((attempt) => <article key={attempt.id} className="flex flex-col gap-2 p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-medium">{format(attempt.startedAt)} {attempt.id === report.baseline?.id ? "· Baseline" : ""}</p><p className="text-sm text-muted-foreground">{attempt.status.replaceAll("_", " ")} · {attempt.completedPdpCount} / {attempt.selectedPdpCount} PDPs · {attempt.summary?.issueCount ?? "—"} issues</p></div><Button variant="ghost" size="sm" asChild><Link href={`/stores/${storeId}/quality/${attempt.id}`}>View report</Link></Button></article>)}</div></section>
  </div>;
}

function Metric({ label, value, detail }: { label: string; value: string; detail?: string }) { return <Card><CardHeader className="gap-1"><CardDescription>{label}</CardDescription><CardTitle className="text-2xl">{value}</CardTitle>{detail && <CardDescription>{detail}</CardDescription>}</CardHeader></Card>; }
function CompletionSummary({ storeId, report }: { storeId: string; report: NonNullable<Awaited<ReturnType<typeof getMonitoringForApp>>>["report"] }) { if (!report) return null; const attempt = report.latestAttempt; const title = attempt.status !== "completed" ? (attempt.status === "failed" ? "Check failed" : attempt.status === "queued" ? "Check queued" : attempt.status === "running" ? "Check running" : "Partial check") : report.comparisonUnavailable ? "Check complete — comparison unavailable" : !report.comparisonPredecessor ? "Baseline established" : report.changes && Object.entries(report.changes).every(([, count]) => count === 0) ? "Check complete — no changes detected" : "Check complete"; const detail = attempt.status !== "completed" ? `${attempt.completedPdpCount} / ${attempt.selectedPdpCount} PDPs checked. ${report.lastConfirmed ? "Confirmed issue state was preserved." : "No confirmed issue state was established."}` : report.changes && Object.entries(report.changes).every(([, count]) => count === 0) ? `${report.currentIssues.length} current issues remain.` : `${attempt.completedPdpCount} / ${attempt.selectedPdpCount} PDPs checked.`; return <Card role="status"><CardHeader><CardTitle>{title}</CardTitle><CardDescription>{detail}</CardDescription></CardHeader><CardContent><Button variant="outline" asChild><Link href={`/stores/${storeId}/quality/${attempt.id}`}>View run</Link></Button></CardContent></Card>; }
function scopeLabel(scope: { kind: "all" | "category" | "uncategorized"; categoryName: string | null }) { return scope.kind === "category" ? (scope.categoryName ?? "Category") : scope.kind === "uncategorized" ? "Uncategorized" : "All products"; }
function format(value: string | null) { return value ? new Date(value).toLocaleString() : "—"; }
